### ISSUE TITLE
Erreur createOrder

### ISSUE THREAD

**Issue by AmityTek** [ylly/certsign#1]
Bonjour,

J'utilise la lib pour faire signer un doc mais impossible de passer la première étape "createOrder"
J'ai une réponse null a chaque fois ... J'envoi parfaitement les données (nom, prenom, email, phone, pays ...)

D'ou pourrait venir le problème ?

**Comment by samuel-queniart** [comment]
did you create the request well ?
like : 
```
$request = Request::create()
    ->setHolder('Firstname', 'Lastname', 'certsign@ylly.fr', '0601020304')
    ->addDocument('Document-1', '/path/to/doc.pdf', $signature, false);
```

What return this lines : https://github.com/ylly/certsign/blob/master/src/Signator.php#L120 ?

**Comment by AmityTek** [comment]
Yes i create the request like your exemple

This line return =>
 +holder: Holder {#425 ▼
    +firstname: "*******"
    +lastname: "******"
    +email: "******"
    +mobile: "*********"
    +country: "FR"
  }
  +otp: OTP {#424 ▼
    +enabled: true
    +contact: "*********"
  }
  +documents: array:1 [▼

**Comment by mickaelblondeau** [comment]
Bonjour,

Il s'agit certainement d'une erreur d'authentification, dans la configuration "cert", vous avez du renseigner le fichier fourni par cert europe, cependant (bien que ce ne soit pas spécifié dans la documentation) le format requis est "PEM", il faut donc extraire le certificat au bon format pour l'utiliser avec cette librairie

Nous allons mettre à jour le readme et planifier une mise à jour pour supporter le format par défaut

**Comment by mickaelblondeau** [comment]
Documentation mise à jour

689e01e1c5ae88bb3c8ce45eb2abdf28af1684f6
